[build]
  publish = "public"
  command = "make prepare && hugo --baseURL $URL"

[context.production.environment]
  HUGO_VERSION = "0.51"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo --enableGitInfo"

[context.split1.environment]
  HUGO_VERSION = "0.51"
  HUGO_ENV = "production"  
  
[context.deploy-preview]
  command = "make prepare && hugo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"
  publish = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.51"
  HUGO_ENV = "development"

[context.branch-deploy.environment]
  HUGO_ENABLEGITINFO = "true"
  HUGO_VERSION = "0.51"  
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
 from = "https://madicetea.com/*"
 to = "https://madicetea.me/:splat"
 status = 301
 force = true

[[redirects]]
 from = "https://www.madicetea.com/*"
 to = "https://madicetea.me/:splat"
 status = 301
 force = true
 
[[redirects]]
 from = "https://madicetea.netlify.com/*"
 to = "https://madicetea.me/:splat"
 status = 301
 force = true
