backend:
  name: git-gateway
  repo: <% GITHUB_REPOSITORY %> # Gulp will replace this with your GitHub repository
  branch: development
  publish_mode: editorial_workflow
  
media_folder: "site/static/images" # Folder where user uploaded files should go
public_folder: "images"